import { ChangeEvent, useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { groupScheduleByReference, type CalendarReference } from "@/lib/calendar";
import { canLoadClientPortal } from "@/lib/access";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import {
  Activity, CalendarDays, Check, ChevronRight, CircleDollarSign, ClipboardList,
  FilePlus2, Files, HeartPulse, ImagePlus, LayoutDashboard, LogOut, Menu,
  PackagePlus, Plus, ReceiptText, Settings2, ShieldCheck, Sparkles, Stethoscope, Users,
  WalletCards, X, type LucideIcon,
} from "lucide-react";
import { toast } from "sonner";

type Section = "inicio" | "agenda" | "clientes" | "servicos" | "questionarios" | "financeiro" | "gestao";

const roleLabel: Record<string, string> = {
  admin: "Gestor(a)", recepcao: "Recepção", profissional: "Profissional", cliente: "Cliente", user: "Cliente",
};

const statusLabel: Record<string, string> = {
  PENDENTE: "Solicitado", AGUARDANDO_CONFIRMACAO: "Aguardando confirmação", CONFIRMADA: "Confirmada",
  EM_ATENDIMENTO: "Em atendimento", CONCLUIDA: "Realizada", CANCELADA: "Cancelada",
  NAO_COMPARECEU: "Falta", BLOQUEADA: "Bloqueada", ABERTA: "Em aberto", PAGA: "Paga",
};

function currency(value: string | number | null | undefined) {
  return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value ?? 0));
}

function dateTime(value: Date | string | null | undefined) {
  if (!value) return "—";
  return new Date(value).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" });
}

function dateOnly(value: Date | string | null | undefined) {
  if (!value) return "—";
  return new Date(value).toLocaleDateString("pt-BR");
}

function exportCommissionReport(rows: Array<{ profissionalNome: string; percentual: string; valor: string; status: string }>) {
  const reportWindow = window.open("", "_blank", "width=900,height=720");
  if (!reportWindow) { toast.error("Permita a abertura de janelas para salvar o relatório em PDF."); return; }
  const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char] ?? char));
  const total = rows.reduce((sum, row) => sum + Number(row.valor), 0);
  reportWindow.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Relatório de comissões — Aura</title><style>body{font-family:Arial,sans-serif;color:#2c2627;margin:40px}h1{font-family:Georgia,serif;margin:0;color:#8f3156}p{color:#6d6264}table{border-collapse:collapse;width:100%;margin-top:28px}th,td{padding:12px;border-bottom:1px solid #eadfe2;text-align:left}th{color:#8f3156;text-transform:uppercase;font-size:11px;letter-spacing:.08em}.total{margin-top:24px;font-size:18px;font-weight:700;text-align:right}@media print{body{margin:22px}}</style></head><body><p>AURA GESTÃO ESTÉTICA</p><h1>Relatório de comissões</h1><p>Emitido em ${new Date().toLocaleString("pt-BR")}</p><table><thead><tr><th>Profissional</th><th>Percentual</th><th>Status</th><th>Valor</th></tr></thead><tbody>${rows.map((row) => `<tr><td>${escapeHtml(row.profissionalNome)}</td><td>${escapeHtml(String(row.percentual))}%</td><td>${escapeHtml(row.status)}</td><td>${currency(row.valor)}</td></tr>`).join("") || "<tr><td colspan='4'>Não há comissões para o período.</td></tr>"}</tbody></table><p class="total">Total: ${currency(total)}</p></body></html>`);
  reportWindow.document.close();
  reportWindow.focus();
  window.setTimeout(() => reportWindow.print(), 150);
}

function StatusBadge({ value }: { value: string }) {
  const className = value === "CONCLUIDA" || value === "PAGA" || value === "CONFIRMADA"
    ? "status-success" : value === "CANCELADA" || value === "NAO_COMPARECEU" ? "status-danger" : "status-neutral";
  return <span className={`status-badge ${className}`}>{statusLabel[value] ?? value}</span>;
}

function SectionHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) {
  return <div className="section-header">
    <div>
      <p className="eyebrow">{eyebrow}</p>
      <h1>{title}</h1>
      <p className="section-description">{description}</p>
    </div>
    {action}
  </div>;
}

function EmptyRow({ cols, message }: { cols: number; message: string }) {
  return <TableRow><TableCell colSpan={cols} className="h-28 text-center text-muted-foreground">{message}</TableCell></TableRow>;
}

function readFileAsDataUrl(file: File) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(new Error("Não foi possível ler a imagem."));
    reader.onload = () => resolve(String(reader.result));
    reader.readAsDataURL(file);
  });
}

export default function Home() {
  const { user, loading, logout } = useAuth();
  const [section, setSection] = useState<Section>("inicio");
  const [mobileMenu, setMobileMenu] = useState(false);
  const [showClientForm, setShowClientForm] = useState(false);
  const [showSessionForm, setShowSessionForm] = useState(false);
  const [showServiceForm, setShowServiceForm] = useState(false);
  const [showQuestionnaireForm, setShowQuestionnaireForm] = useState(false);
  const [showExpenseForm, setShowExpenseForm] = useState(false);
  const [showEquipmentForm, setShowEquipmentForm] = useState(false);
  const [showSupplyForm, setShowSupplyForm] = useState(false);
  const [calendarReference, setCalendarReference] = useState<CalendarReference>("profissional");
  const [weekReference, setWeekReference] = useState(() => {
    const day = new Date();
    day.setHours(0, 0, 0, 0);
    day.setDate(day.getDate() - ((day.getDay() + 6) % 7));
    return day.getTime();
  });
  const [selectedClientId, setSelectedClientId] = useState<number | null>(null);
  const [photoFile, setPhotoFile] = useState<File | null>(null);
  const [photoCategory, setPhotoCategory] = useState<"ANTES" | "DEPOIS" | "EVOLUCAO">("EVOLUCAO");
  const [clientForm, setClientForm] = useState({ nome: "", email: "", telefone: "", cpfHash: "", dataNascimento: "" });
  const [sessionForm, setSessionForm] = useState({ clienteId: "", servicoId: "", profissionalId: "", dataHoraInicio: "", duracaoMin: "60" });
  const [serviceForm, setServiceForm] = useState({ nome: "", valor: "", duracaoMin: "60", descricao: "" });
  const [questionnaireForm, setQuestionnaireForm] = useState({ codigo: "", nome: "", descricao: "", texto: "", tipoResposta: "TEXTO" as const });
  const [expenseForm, setExpenseForm] = useState({ descricao: "", categoria: "", valor: "", dataCompetencia: new Date().toISOString().slice(0, 10) });
  const [equipmentForm, setEquipmentForm] = useState({ id: null as number | null, nome: "", tipo: "", localizacao: "", descricao: "" });
  const [supplyForm, setSupplyForm] = useState({ id: null as number | null, nome: "", unidade: "un", estoqueAtual: "", estoqueMinimo: "", custoUnitario: "" });
  const [recordForm, setRecordForm] = useState({ alergias: "", restricoes: "", observacoesClinicas: "" });
  const [portalQuestionnaireId, setPortalQuestionnaireId] = useState<number | null>(null);
  const [portalAnswers, setPortalAnswers] = useState<Record<number, string>>({});
  const [portalSignature, setPortalSignature] = useState("");
  const utils = trpc.useUtils();

  const role = user?.role ?? "user";
  const isStaff = ["admin", "recepcao", "profissional"].includes(role);
  const isManager = ["admin", "recepcao"].includes(role);
  const isAdmin = role === "admin";
  const isClient = role === "cliente" || role === "user";
  const clientPortalEnabled = canLoadClientPortal(user, loading);

  const statsQuery = trpc.financeiro.dashboardStats.useQuery(undefined, { enabled: isStaff });
  const clientsQuery = trpc.clientes.list.useQuery(undefined, { enabled: isStaff });
  const servicesQuery = trpc.servicos.list.useQuery(undefined, { enabled: Boolean(user) });
  const sessionsQuery = trpc.sessoes.list.useQuery(undefined, { enabled: isStaff });
  const accountsQuery = trpc.financeiro.contas.useQuery(undefined, { enabled: isManager });
  const questionnairesQuery = trpc.questionarios.list.useQuery(undefined, { enabled: isStaff });
  const professionalsQuery = trpc.profissionais.list.useQuery(undefined, { enabled: isManager });
  const expensesQuery = trpc.financeiro.despesas.useQuery(undefined, { enabled: isAdmin });
  const cashQuery = trpc.financeiro.caixa.useQuery(undefined, { enabled: isManager });
  const commissionQuery = trpc.financeiro.comissoes.useQuery(undefined, { enabled: isAdmin });
  const clientDetailQuery = trpc.clientes.get.useQuery({ id: selectedClientId ?? 0 }, { enabled: selectedClientId !== null && isStaff });
  const portalQuery = trpc.portal.resumo.useQuery(undefined, { enabled: clientPortalEnabled });
  const bookingOptionsQuery = trpc.portal.opcoesAgendamento.useQuery(undefined, { enabled: clientPortalEnabled });
  const portalQuestionnaireQuery = trpc.questionarios.get.useQuery({ id: portalQuestionnaireId ?? 0 }, { enabled: clientPortalEnabled && portalQuestionnaireId !== null });
  const usersQuery = trpc.auth.listUsers.useQuery(undefined, { enabled: isAdmin });
  const reminderQuery = trpc.lembretes.list.useQuery(undefined, { enabled: isAdmin });
  const equipmentQuery = trpc.recursos.equipamentos.list.useQuery(undefined, { enabled: isStaff });
  const suppliesQuery = trpc.recursos.insumos.list.useQuery(undefined, { enabled: isStaff });

  const createClient = trpc.clientes.create.useMutation({
    onSuccess: () => { toast.success("Cliente cadastrado e prontuário criado."); setShowClientForm(false); setClientForm({ nome: "", email: "", telefone: "", cpfHash: "", dataNascimento: "" }); utils.clientes.list.invalidate(); },
    onError: (error) => toast.error(error.message),
  });
  const createSession = trpc.sessoes.create.useMutation({
    onSuccess: () => { toast.success("Agendamento registrado e lembretes preparados."); setShowSessionForm(false); utils.sessoes.list.invalidate(); utils.financeiro.contas.invalidate(); utils.financeiro.dashboardStats.invalidate(); },
    onError: (error) => toast.error(error.message),
  });
  const updateStatus = trpc.sessoes.updateStatus.useMutation({
    onSuccess: () => { toast.success("Status atualizado."); utils.sessoes.list.invalidate(); utils.financeiro.dashboardStats.invalidate(); },
    onError: (error) => toast.error(error.message),
  });
  const createService = trpc.servicos.create.useMutation({ onSuccess: () => { toast.success("Procedimento cadastrado."); setShowServiceForm(false); utils.servicos.list.invalidate(); }, onError: (error) => toast.error(error.message) });
  const createQuestionnaire = trpc.questionarios.create.useMutation({ onSuccess: () => { toast.success("Questionário publicado como nova versão."); setShowQuestionnaireForm(false); utils.questionarios.list.invalidate(); }, onError: (error) => toast.error(error.message) });
  const receivePayment = trpc.financeiro.receber.useMutation({ onSuccess: () => { toast.success("Recebimento registrado."); utils.financeiro.contas.invalidate(); utils.financeiro.dashboardStats.invalidate(); utils.financeiro.caixa.invalidate(); }, onError: (error) => toast.error(error.message) });
  const createExpense = trpc.financeiro.criarDespesa.useMutation({ onSuccess: () => { toast.success("Despesa lançada."); setShowExpenseForm(false); utils.financeiro.despesas.invalidate(); }, onError: (error) => toast.error(error.message) });
  const payExpense = trpc.financeiro.marcarDespesaPaga.useMutation({ onSuccess: () => { toast.success("Despesa marcada como paga."); utils.financeiro.despesas.invalidate(); utils.financeiro.caixa.invalidate(); }, onError: (error) => toast.error(error.message) });
  const updateRecord = trpc.prontuario.update.useMutation({ onSuccess: () => { toast.success("Prontuário atualizado."); utils.clientes.get.invalidate(); }, onError: (error) => toast.error(error.message) });
  const uploadPhoto = trpc.prontuario.uploadPhoto.useMutation({ onSuccess: () => { toast.success("Foto clínica armazenada com segurança."); setPhotoFile(null); utils.clientes.get.invalidate(); }, onError: (error) => toast.error(error.message) });
  const requestBooking = trpc.portal.solicitarAgendamento.useMutation({ onSuccess: () => { toast.success("Solicitação de agendamento enviada para a clínica."); utils.portal.resumo.invalidate(); }, onError: (error) => toast.error(error.message) });
  const answerQuestionnaire = trpc.questionarios.responder.useMutation({ onSuccess: () => { toast.success("Anamnese assinada e registrada no seu histórico."); setPortalQuestionnaireId(null); setPortalAnswers({}); setPortalSignature(""); utils.portal.resumo.invalidate(); }, onError: (error) => toast.error(error.message) });
  const updateUserRole = trpc.auth.updateRole.useMutation({ onSuccess: () => { toast.success("Perfil atualizado."); utils.auth.listUsers.invalidate(); }, onError: (error) => toast.error(error.message) });
  const createEquipment = trpc.recursos.equipamentos.create.useMutation({ onSuccess: () => { toast.success("Equipamento cadastrado."); setShowEquipmentForm(false); setEquipmentForm({ id: null, nome: "", tipo: "", localizacao: "", descricao: "" }); utils.recursos.equipamentos.invalidate(); }, onError: (error) => toast.error(error.message) });
  const updateEquipment = trpc.recursos.equipamentos.update.useMutation({ onSuccess: () => { toast.success("Equipamento atualizado."); setShowEquipmentForm(false); setEquipmentForm({ id: null, nome: "", tipo: "", localizacao: "", descricao: "" }); utils.recursos.equipamentos.invalidate(); }, onError: (error) => toast.error(error.message) });
  const createSupply = trpc.recursos.insumos.create.useMutation({ onSuccess: () => { toast.success("Insumo cadastrado."); setShowSupplyForm(false); setSupplyForm({ id: null, nome: "", unidade: "un", estoqueAtual: "", estoqueMinimo: "", custoUnitario: "" }); utils.recursos.insumos.invalidate(); }, onError: (error) => toast.error(error.message) });
  const updateSupply = trpc.recursos.insumos.update.useMutation({ onSuccess: () => { toast.success("Insumo atualizado."); setShowSupplyForm(false); setSupplyForm({ id: null, nome: "", unidade: "un", estoqueAtual: "", estoqueMinimo: "", custoUnitario: "" }); utils.recursos.insumos.invalidate(); }, onError: (error) => toast.error(error.message) });

  const selectedDetail = clientDetailQuery.data;
  const clientName = selectedDetail?.client.nome ?? "";
  const upcomingSessions = useMemo(() => sessionsQuery.data?.filter((session) => new Date(session.dataHoraInicio) >= new Date() && !["CANCELADA", "NAO_COMPARECEU"].includes(session.status)).slice(0, 6) ?? [], [sessionsQuery.data]);
  const weekDays = useMemo(() => Array.from({ length: 7 }, (_, index) => {
    const day = new Date(weekReference);
    day.setDate(day.getDate() + index);
    return day;
  }), [weekReference]);
  const sessionsByWeekDay = useMemo(() => weekDays.map((day) => {
    const nextDay = new Date(day);
    nextDay.setDate(nextDay.getDate() + 1);
    const daySessions = (sessionsQuery.data ?? []).filter((session) => {
      const sessionDate = new Date(session.dataHoraInicio);
      return sessionDate >= day && sessionDate < nextDay;
    });
    return groupScheduleByReference(daySessions, calendarReference);
  }), [sessionsQuery.data, weekDays, calendarReference]);

  const openClient = (id: number) => {
    setSelectedClientId(id);
    const local = clientsQuery.data?.find((client) => client.id === id);
    setRecordForm({ alergias: "", restricoes: "", observacoesClinicas: local?.observacoesInternas ?? "" });
  };

  if (loading) return <div className="app-loading"><Sparkles className="animate-pulse" /> <span>Preparando sua experiência Aura.</span></div>;

  if (!user) {
    return <main className="login-shell"><div className="login-card"><div className="brand-mark"><Sparkles /></div><p className="eyebrow">GESTÃO PARA CLÍNICA ESTÉTICA</p><h1>Rotina clínica, financeira e de atendimento em um só lugar.</h1><p>Entre com sua conta para acessar o ambiente destinado ao seu perfil.</p><Button onClick={() => window.location.href = "/entrar"} className="primary-action">Acessar o sistema <ChevronRight /></Button></div></main>;
  }

  if (isClient) {
    const appointments = portalQuery.data?.agendamentos ?? [];
    const options = bookingOptionsQuery.data;
    return <main className="portal-shell">
      <header className="portal-header"><div className="brand-lockup"><div className="brand-mark"><Sparkles /></div><div><strong>Aura</strong><span>Estética avançada</span></div></div><div className="profile-compact"><span>Olá, {user.name?.split(" ")[0] ?? "Cliente"}</span><Button variant="ghost" size="sm" onClick={() => logout()}><LogOut /></Button></div></header>
      <section className="portal-hero"><div><p className="eyebrow">PORTAL DO CLIENTE</p><h1>Seu cuidado, sempre ao alcance.</h1><p>Confira agendamentos e solicite seu próximo atendimento diretamente à clínica.</p></div><div className="portal-stat"><CalendarDays /><strong>{appointments.filter((session) => new Date(session.dataHoraInicio) >= new Date()).length}</strong><span>próximos horários</span></div></section>
      <section className="portal-grid">
        <Card className="surface-card"><CardHeader><CardTitle>Próximos atendimentos</CardTitle><CardDescription>Confirme os detalhes com a clínica quando necessário.</CardDescription></CardHeader><CardContent className="space-y-3">{appointments.filter((session) => new Date(session.dataHoraInicio) >= new Date()).slice(0, 4).map((session) => <div className="appointment-line" key={session.id}><CalendarDays /><div><strong>{dateTime(session.dataHoraInicio)}</strong><span><StatusBadge value={session.status} /></span></div></div>)}{appointments.filter((session) => new Date(session.dataHoraInicio) >= new Date()).length === 0 && <p className="empty-copy">Você ainda não possui atendimentos futuros.</p>}</CardContent></Card>
        <Card className="surface-card"><CardHeader><CardTitle>Solicitar agendamento</CardTitle><CardDescription>Envie uma solicitação para avaliação da recepção.</CardDescription></CardHeader><CardContent className="space-y-4"><Select onValueChange={(value) => setSessionForm((form) => ({ ...form, servicoId: value, duracaoMin: String(options?.servicos.find((service) => String(service.id) === value)?.duracaoMin ?? 60) }))}><SelectTrigger><SelectValue placeholder="Escolha o procedimento" /></SelectTrigger><SelectContent>{options?.servicos.map((service) => <SelectItem key={service.id} value={String(service.id)}>{service.nome} · {currency(service.valor)}</SelectItem>)}</SelectContent></Select><Select onValueChange={(value) => setSessionForm((form) => ({ ...form, profissionalId: value }))}><SelectTrigger><SelectValue placeholder="Profissional de preferência" /></SelectTrigger><SelectContent>{options?.profissionais.map((professional) => <SelectItem key={professional.id} value={String(professional.id)}>{professional.name ?? "Profissional"}</SelectItem>)}</SelectContent></Select><Input type="datetime-local" onChange={(event) => setSessionForm((form) => ({ ...form, dataHoraInicio: event.target.value }))} /><Button className="primary-action w-full" disabled={!sessionForm.servicoId || !sessionForm.profissionalId || !sessionForm.dataHoraInicio || requestBooking.isPending} onClick={() => requestBooking.mutate({ servicoId: Number(sessionForm.servicoId), profissionalId: Number(sessionForm.profissionalId), dataHoraInicio: new Date(sessionForm.dataHoraInicio), duracaoMin: Number(sessionForm.duracaoMin) })}>Solicitar horário</Button></CardContent></Card>
        <Card className="surface-card portal-questionnaire"><CardHeader><CardTitle>Anamnese pendente</CardTitle><CardDescription>Preencha e assine os formulários solicitados para seu atendimento.</CardDescription></CardHeader><CardContent className="space-y-4">{portalQuery.data?.questionariosPendentes.map((questionnaire) => <button key={questionnaire.id} className="questionnaire-choice" onClick={() => { setPortalQuestionnaireId(questionnaire.id); setPortalAnswers({}); setPortalSignature(user.name ?? ""); }}><ClipboardList /><span><strong>{questionnaire.nome}</strong><small>Versão {questionnaire.versao}</small></span><ChevronRight /></button>)}{!portalQuery.data?.questionariosPendentes.length && <p className="empty-copy">Nenhum formulário pendente.</p>}</CardContent></Card>
        {portalQuestionnaireId && portalQuestionnaireQuery.data && <Card className="surface-card portal-answer-card"><CardHeader><div><p className="eyebrow">ANAMNESE</p><CardTitle>{portalQuestionnaireQuery.data.nome}</CardTitle><CardDescription>Preencha as respostas e confirme a declaração de veracidade.</CardDescription></div><Button variant="ghost" size="icon" onClick={() => setPortalQuestionnaireId(null)}><X /></Button></CardHeader><CardContent className="form-stack">{portalQuestionnaireQuery.data.perguntas.map((question) => <div className="field" key={question.id}><Label>{question.ordem}. {question.texto}{question.obrigatoria ? " *" : ""}</Label>{question.tipoResposta === "BOOLEAN" ? <Select value={portalAnswers[question.id ?? 0]} onValueChange={(value) => setPortalAnswers((answers) => ({ ...answers, [question.id ?? 0]: value }))}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent><SelectItem value="true">Sim</SelectItem><SelectItem value="false">Não</SelectItem></SelectContent></Select> : <Input type={question.tipoResposta === "DATA" ? "date" : question.tipoResposta === "NUMERO" ? "number" : "text"} value={portalAnswers[question.id ?? 0] ?? ""} onChange={(event) => setPortalAnswers((answers) => ({ ...answers, [question.id ?? 0]: event.target.value }))} />}</div>)}<div className="field"><Label>Assinatura digital (nome completo)</Label><Input value={portalSignature} onChange={(event) => setPortalSignature(event.target.value)} placeholder="Digite seu nome completo" /></div><p className="declaration-copy">Ao enviar, declaro que as informações são verdadeiras e autorizo seu registro no meu prontuário.</p><Button className="primary-action" disabled={!portalQuery.data?.clientId || portalSignature.trim().length < 4 || answerQuestionnaire.isPending} onClick={() => { const questions = portalQuestionnaireQuery.data?.perguntas ?? []; answerQuestionnaire.mutate({ clienteId: portalQuery.data!.clientId!, questionarioId: portalQuestionnaireId, declaracaoVeracidade: true, assinaturaDigital: portalSignature.trim(), respostas: questions.map((question) => question.tipoResposta === "BOOLEAN" ? { perguntaId: question.id!, respostaBoolean: portalAnswers[question.id!] === "true" } : question.tipoResposta === "NUMERO" ? { perguntaId: question.id!, respostaNumero: portalAnswers[question.id!] || "0" } : { perguntaId: question.id!, respostaTexto: portalAnswers[question.id!] ?? "" }) }); }}>Assinar e enviar</Button></CardContent></Card>}
      </section>
    </main>;
  }

  const nav: { id: Section; label: string; icon: LucideIcon; visible: boolean }[] = [
    { id: "inicio", label: "Visão geral", icon: LayoutDashboard, visible: true }, { id: "agenda", label: "Agenda", icon: CalendarDays, visible: true },
    { id: "clientes", label: "Clientes", icon: Users, visible: true }, { id: "servicos", label: "Serviços", icon: Sparkles, visible: isAdmin },
    { id: "questionarios", label: "Anamnese", icon: ClipboardList, visible: true }, { id: "financeiro", label: "Financeiro", icon: WalletCards, visible: isManager },
    { id: "gestao", label: "Gestão", icon: Settings2, visible: isAdmin },
  ];

  return <div className="clinic-shell">
    <aside className={`sidebar ${mobileMenu ? "sidebar-open" : ""}`}>
      <div className="sidebar-brand"><div className="brand-mark"><Sparkles /></div><div><strong>Aura</strong><span>Gestão estética</span></div><Button variant="ghost" size="icon" className="mobile-close" onClick={() => setMobileMenu(false)}><X /></Button></div>
      <nav>{nav.filter((item) => item.visible).map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => { setSection(item.id); setMobileMenu(false); }} className={`nav-item ${section === item.id ? "nav-active" : ""}`}><Icon /><span>{item.label}</span></button>; })}</nav>
      <div className="sidebar-footer"><div className="profile-card"><span className="profile-initial">{user.name?.slice(0, 1).toUpperCase() ?? "A"}</span><div><strong>{user.name ?? "Usuário"}</strong><span>{roleLabel[role]}</span></div></div><Button variant="ghost" size="sm" onClick={() => logout()} className="logout-action"><LogOut /> Sair</Button></div>
    </aside>
    <div className="dashboard-area">
      <header className="mobile-topbar"><Button variant="ghost" size="icon" onClick={() => setMobileMenu(true)}><Menu /></Button><div className="brand-lockup"><div className="brand-mark"><Sparkles /></div><strong>Aura</strong></div></header>
      <main className="dashboard-main">
        {section === "inicio" && <>
          <SectionHeader eyebrow="PAINEL OPERACIONAL" title="Bom dia, sua clínica está em movimento." description="Acompanhe os indicadores e prioridades da operação de hoje." action={<div className="header-actions">{isManager && <Button variant="outline" onClick={() => setShowClientForm(true)}><Users /> Novo cliente</Button>}<Button className="primary-action" onClick={() => setShowSessionForm(true)}><Plus /> Agendamento</Button></div>} />
          <div className="metric-grid"><Metric icon={CircleDollarSign} label="Faturamento do mês" value={currency(statsQuery.data?.faturamentoMes)} /><Metric icon={CalendarDays} label="Agenda de hoje" value={String(statsQuery.data?.agendamentosHoje ?? 0)} /><Metric icon={Activity} label="Taxa de ocupação" value={`${statsQuery.data?.taxaOcupacao ?? 0}%`} /><Metric icon={Users} label="Clientes ativos" value={String(statsQuery.data?.clientesTotal ?? 0)} /></div>
          <div className="dashboard-grid"><Card className="surface-card large-card"><CardHeader><div><p className="eyebrow">PRÓXIMOS ATENDIMENTOS</p><CardTitle>Agenda em sequência</CardTitle></div><Button variant="outline" size="sm" onClick={() => setSection("agenda")}>Ver agenda</Button></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Horário</TableHead><TableHead>Cliente</TableHead><TableHead>Procedimento</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{upcomingSessions.map((session) => <TableRow key={session.id}><TableCell>{dateTime(session.dataHoraInicio)}</TableCell><TableCell className="font-medium">{session.clienteNome}</TableCell><TableCell>{session.servicoNome}</TableCell><TableCell><StatusBadge value={session.status} /></TableCell></TableRow>)}{upcomingSessions.length === 0 && <EmptyRow cols={4} message="Nenhum agendamento futuro encontrado." />}</TableBody></Table></CardContent></Card><Card className="surface-card"><CardHeader><p className="eyebrow">ATENÇÃO ESPECIAL</p><CardTitle>Aniversariantes de hoje</CardTitle></CardHeader><CardContent>{(statsQuery.data?.aniversariantes ?? []).length ? <ul className="simple-list">{statsQuery.data?.aniversariantes.map((name) => <li key={name}><Sparkles /> {name}</li>)}</ul> : <p className="empty-copy">Não há aniversariantes registrados para hoje.</p>}<div className="reminder-note"><ShieldCheck /><span>Os lembretes são preparados ao criar novos agendamentos.</span></div></CardContent></Card></div>
        </>}

        {section === "agenda" && <>
          <SectionHeader eyebrow="OPERAÇÃO CLÍNICA" title="Agenda e atendimentos" description="Visualize o calendário por horário e atualize o estado de cada sessão." action={<Button className="primary-action" onClick={() => setShowSessionForm(true)}><Plus /> Novo agendamento</Button>} />
          <Card className="surface-card agenda-calendar"><CardHeader><div><p className="eyebrow">CALENDÁRIO SEMANAL</p><CardTitle>Visão por {calendarReference === "profissional" ? "profissional" : calendarReference === "sala" ? "sala" : "procedimento"}</CardTitle><CardDescription>{weekDays[0]?.toLocaleDateString("pt-BR", { day: "2-digit", month: "short" })} a {weekDays[6]?.toLocaleDateString("pt-BR", { day: "2-digit", month: "short", year: "numeric" })}</CardDescription></div><div className="calendar-controls"><div className="calendar-nav"><Button size="sm" variant="outline" onClick={() => setWeekReference((value) => value - 7 * 24 * 60 * 60 * 1000)}>Anterior</Button><Button size="sm" variant="outline" onClick={() => { const today = new Date(); today.setHours(0, 0, 0, 0); today.setDate(today.getDate() - ((today.getDay() + 6) % 7)); setWeekReference(today.getTime()); }}>Hoje</Button><Button size="sm" variant="outline" onClick={() => setWeekReference((value) => value + 7 * 24 * 60 * 60 * 1000)}>Próxima</Button></div><Select value={calendarReference} onValueChange={(value) => setCalendarReference(value as typeof calendarReference)}><SelectTrigger className="calendar-select"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="profissional">Por profissional</SelectItem><SelectItem value="sala">Por sala</SelectItem><SelectItem value="procedimento">Por procedimento</SelectItem></SelectContent></Select></div></CardHeader><CardContent><div className="weekly-calendar">{weekDays.map((day, index) => <div className="calendar-day" key={day.toISOString()}><div className="calendar-day-label"><strong>{day.toLocaleDateString("pt-BR", { weekday: "short" }).replace(".", "")}</strong><span>{day.getDate()}</span></div><div className="calendar-events">{sessionsByWeekDay[index]?.map((group) => <div className="calendar-group" key={group.label}><p>{group.label}</p>{group.sessions.map((session) => <div className="calendar-event" key={session.id}><span>{new Date(session.dataHoraInicio).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</span><strong>{session.clienteNome}</strong><small>{session.servicoNome}</small></div>)}</div>)}{!sessionsByWeekDay[index]?.length && <p className="calendar-empty">Sem atendimentos</p>}</div></div>)}</div></CardContent></Card>
          <Card className="surface-card"><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Data e horário</TableHead><TableHead>Cliente</TableHead><TableHead>Procedimento</TableHead><TableHead>Profissional</TableHead><TableHead>Sala</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Ações</TableHead></TableRow></TableHeader><TableBody>{sessionsQuery.data?.map((session) => <TableRow key={session.id}><TableCell>{dateTime(session.dataHoraInicio)}</TableCell><TableCell className="font-medium">{session.clienteNome}</TableCell><TableCell>{session.servicoNome}</TableCell><TableCell>{session.profissionalNome}</TableCell><TableCell>{session.salaNome ?? "—"}</TableCell><TableCell><StatusBadge value={session.status} /></TableCell><TableCell className="text-right"><div className="inline-actions">{["PENDENTE", "AGUARDANDO_CONFIRMACAO"].includes(session.status) && <Button size="sm" variant="outline" onClick={() => updateStatus.mutate({ id: session.id, status: "CONFIRMADA" })}>Confirmar</Button>}{["CONFIRMADA", "EM_ATENDIMENTO"].includes(session.status) && <Button size="sm" className="complete-action" onClick={() => updateStatus.mutate({ id: session.id, status: "CONCLUIDA" })}><Check /> Realizada</Button>}</div></TableCell></TableRow>)}{!sessionsQuery.data?.length && <EmptyRow cols={7} message="Nenhuma sessão registrada." />}</TableBody></Table></CardContent></Card>
        </>}

        {section === "clientes" && <>
          <SectionHeader eyebrow="RELACIONAMENTO E PRONTUÁRIO" title="Clientes" description="Cadastros, histórico clínico, evolução e registro de imagens com acesso controlado." action={isManager ? <Button className="primary-action" onClick={() => setShowClientForm(true)}><Plus /> Novo cliente</Button> : undefined} />
          <div className="clients-layout"><Card className="surface-card"><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>Contato</TableHead><TableHead>Cadastro</TableHead><TableHead /></TableRow></TableHeader><TableBody>{clientsQuery.data?.map((client) => <TableRow key={client.id}><TableCell><div className="client-name"><span>{client.nome.slice(0, 1)}</span><div><strong>{client.nome}</strong><small>{client.status}</small></div></div></TableCell><TableCell>{client.telefone ?? client.email ?? "—"}</TableCell><TableCell>{dateOnly(client.createdAt)}</TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={() => openClient(client.id)}>Prontuário</Button></TableCell></TableRow>)}{!clientsQuery.data?.length && <EmptyRow cols={4} message="Nenhum cliente cadastrado." />}</TableBody></Table></CardContent></Card>
          {selectedClientId && <Card className="surface-card record-card"><CardHeader><div><p className="eyebrow">PRONTUÁRIO ELETRÔNICO</p><CardTitle>{clientName || "Carregando cliente"}</CardTitle><CardDescription>Dados clínicos e documentos protegidos por perfil de acesso.</CardDescription></div><Button variant="ghost" size="icon" onClick={() => setSelectedClientId(null)}><X /></Button></CardHeader><CardContent className="space-y-5"><div className="record-fields"><div><Label>Alergias</Label><Textarea defaultValue={selectedDetail?.record?.alergias ?? ""} onChange={(event) => setRecordForm((form) => ({ ...form, alergias: event.target.value }))} /></div><div><Label>Restrições</Label><Textarea defaultValue={selectedDetail?.record?.restricoes ?? ""} onChange={(event) => setRecordForm((form) => ({ ...form, restricoes: event.target.value }))} /></div><div className="full-row"><Label>Observações clínicas</Label><Textarea defaultValue={selectedDetail?.record?.observacoesClinicas ?? ""} onChange={(event) => setRecordForm((form) => ({ ...form, observacoesClinicas: event.target.value }))} /></div></div><Button variant="outline" onClick={() => updateRecord.mutate({ clienteId: selectedClientId, ...recordForm })} disabled={updateRecord.isPending}>Salvar prontuário</Button><div className="record-divider" /><div><h3>Registro de imagem</h3><p className="subtle-copy">A imagem fica associada exclusivamente ao prontuário deste cliente.</p><div className="photo-upload"><Select value={photoCategory} onValueChange={(value) => setPhotoCategory(value as typeof photoCategory)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ANTES">Antes</SelectItem><SelectItem value="DEPOIS">Depois</SelectItem><SelectItem value="EVOLUCAO">Evolução</SelectItem></SelectContent></Select><Input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event: ChangeEvent<HTMLInputElement>) => setPhotoFile(event.target.files?.[0] ?? null)} /><Button variant="outline" disabled={!photoFile || uploadPhoto.isPending} onClick={async () => { if (!photoFile) return; try { uploadPhoto.mutate({ clienteId: selectedClientId, categoria: photoCategory, dataUrl: await readFileAsDataUrl(photoFile) }); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível preparar a imagem."); } }}><ImagePlus /> Enviar</Button></div></div><div><h3>Histórico de sessões</h3><div className="history-list">{selectedDetail?.history.slice(0, 4).map((session) => <div key={session.id}><CalendarDays /><span>{dateTime(session.dataHoraInicio)}</span><StatusBadge value={session.status} /></div>)}{!selectedDetail?.history.length && <p className="empty-copy">Ainda não há sessões no histórico.</p>}</div></div></CardContent></Card>}</div>
        </>}

        {section === "servicos" && <>
          <SectionHeader eyebrow="CATÁLOGO CLÍNICO" title="Serviços e recursos" description="Procedimentos, duração e valor base para o agendamento e o financeiro." action={<div className="header-actions"><Button variant="outline" onClick={() => { setEquipmentForm({ id: null, nome: "", tipo: "", localizacao: "", descricao: "" }); setShowEquipmentForm(true); }}><Plus /> Equipamento</Button><Button className="primary-action" onClick={() => setShowServiceForm(true)}><Plus /> Novo serviço</Button></div>} />
          <Card className="surface-card"><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Procedimento</TableHead><TableHead>Duração</TableHead><TableHead>Valor</TableHead><TableHead>Questionário</TableHead></TableRow></TableHeader><TableBody>{servicesQuery.data?.map((service) => <TableRow key={service.id}><TableCell><strong>{service.nome}</strong><small className="block">{service.descricao ?? "Sem descrição complementar"}</small></TableCell><TableCell>{service.duracaoMin} min</TableCell><TableCell>{currency(service.valor)}</TableCell><TableCell>{service.exigeQuestionario ? <span className="inline-okay"><Check /> Necessário</span> : "Não exigido"}</TableCell></TableRow>)}{!servicesQuery.data?.length && <EmptyRow cols={4} message="Nenhum procedimento ativo cadastrado." />}</TableBody></Table></CardContent></Card>
          <Card className="surface-card mt-5"><CardHeader><div><p className="eyebrow">RECURSOS OPERACIONAIS</p><CardTitle>Equipamentos disponíveis</CardTitle><CardDescription>Itens ativos que podem ser selecionados nos atendimentos.</CardDescription></div></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Equipamento</TableHead><TableHead>Tipo</TableHead><TableHead>Localização</TableHead><TableHead>Próxima manutenção</TableHead><TableHead /></TableRow></TableHeader><TableBody>{equipmentQuery.data?.map((equipment) => <TableRow key={equipment.id}><TableCell className="font-medium">{equipment.nome}</TableCell><TableCell>{equipment.tipo ?? "—"}</TableCell><TableCell>{equipment.localizacao ?? "—"}</TableCell><TableCell>{dateOnly(equipment.proximaManutencaoEm)}</TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={() => { setEquipmentForm({ id: equipment.id, nome: equipment.nome, tipo: equipment.tipo ?? "", localizacao: equipment.localizacao ?? "", descricao: equipment.descricao ?? "" }); setShowEquipmentForm(true); }}>Editar</Button></TableCell></TableRow>)}{!equipmentQuery.data?.length && <EmptyRow cols={5} message="Nenhum equipamento ativo cadastrado." />}</TableBody></Table></CardContent></Card>
        </>}

        {section === "questionarios" && <>
          <SectionHeader eyebrow="ANAMNESE" title="Questionários versionados" description="Crie formulários por procedimento e preserve a assinatura registrada no histórico do cliente." action={isAdmin ? <Button className="primary-action" onClick={() => setShowQuestionnaireForm(true)}><FilePlus2 /> Novo questionário</Button> : undefined} />
          <Card className="surface-card"><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Questionário</TableHead><TableHead>Código</TableHead><TableHead>Versão</TableHead><TableHead>Publicação</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{questionnairesQuery.data?.map((questionnaire) => <TableRow key={questionnaire.id}><TableCell className="font-medium">{questionnaire.nome}</TableCell><TableCell>{questionnaire.codigo ?? "—"}</TableCell><TableCell>v{questionnaire.versao}</TableCell><TableCell>{dateOnly(questionnaire.publicadoEm)}</TableCell><TableCell><StatusBadge value={questionnaire.ativo ? "CONFIRMADA" : "CANCELADA"} /></TableCell></TableRow>)}{!questionnairesQuery.data?.length && <EmptyRow cols={5} message="Nenhum questionário publicado." />}</TableBody></Table></CardContent></Card>
        </>}

        {section === "financeiro" && <>
          <SectionHeader eyebrow="GESTÃO FINANCEIRA" title="Financeiro e caixa" description="Controle recebimentos, despesas, saldo diário e comissões por profissional." action={isAdmin ? <div className="header-actions"><Button variant="outline" onClick={() => exportCommissionReport(commissionQuery.data ?? [])}><Files /> Exportar comissões</Button><Button className="primary-action" onClick={() => setShowExpenseForm(true)}><PackagePlus /> Lançar despesa</Button></div> : undefined} />
          <div className="metric-grid"><Metric icon={ReceiptText} label="Entradas de hoje" value={currency(cashQuery.data?.entradas)} /><Metric icon={WalletCards} label="Saídas de hoje" value={currency(cashQuery.data?.saidas)} /><Metric icon={CircleDollarSign} label="Saldo calculado" value={currency(cashQuery.data?.saldoCalculado)} /><Metric icon={Files} label="Comissões pendentes" value={String(commissionQuery.data?.filter((item) => item.status === "PENDENTE").length ?? 0)} /></div>
          <div className="dashboard-grid finance-grid"><Card className="surface-card large-card"><CardHeader><CardTitle>Contas a receber</CardTitle><CardDescription>Registre o recebimento somente após a confirmação do pagamento.</CardDescription></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>Descrição</TableHead><TableHead>Valor</TableHead><TableHead>Vencimento</TableHead><TableHead>Status</TableHead><TableHead /></TableRow></TableHeader><TableBody>{accountsQuery.data?.map((account) => <TableRow key={account.id}><TableCell className="font-medium">{account.clienteNome}</TableCell><TableCell>{account.descricao}</TableCell><TableCell>{currency(account.valorFinal)}</TableCell><TableCell>{account.dataVencimento}</TableCell><TableCell><StatusBadge value={account.status} /></TableCell><TableCell>{account.status !== "PAGA" && <Button variant="outline" size="sm" onClick={() => receivePayment.mutate({ contaReceberId: account.id, clienteId: account.clienteId, valor: String(account.valorFinal), tipoPagamento: "PIX" })}>Registrar PIX</Button>}</TableCell></TableRow>)}{!accountsQuery.data?.length && <EmptyRow cols={6} message="Nenhuma conta a receber." />}</TableBody></Table></CardContent></Card><Card className="surface-card"><CardHeader><CardTitle>Despesas recentes</CardTitle><CardDescription>Somente lançamentos administrativos.</CardDescription></CardHeader><CardContent className="space-y-2">{expensesQuery.data?.slice(0, 5).map((expense) => <div className="expense-line" key={expense.id}><div><strong>{expense.descricao}</strong><span>{expense.categoria} · {expense.dataCompetencia}</span></div><div><strong>{currency(expense.valor)}</strong>{expense.status !== "PAGA" && <Button size="sm" variant="ghost" onClick={() => payExpense.mutate({ id: expense.id })}>Pagar</Button>}</div></div>)}{!expensesQuery.data?.length && <p className="empty-copy">Nenhuma despesa registrada.</p>}</CardContent></Card></div>
          {isAdmin && <Card className="surface-card mt-5"><CardHeader><CardTitle>Comissões por profissional</CardTitle><CardDescription>Valores gerados para sessões concluídas. Use a exportação para salvar o relatório em PDF.</CardDescription></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Profissional</TableHead><TableHead>Percentual</TableHead><TableHead>Valor</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{commissionQuery.data?.map((commission) => <TableRow key={commission.id}><TableCell className="font-medium">{commission.profissionalNome}</TableCell><TableCell>{commission.percentual}%</TableCell><TableCell>{currency(commission.valor)}</TableCell><TableCell><StatusBadge value={commission.status} /></TableCell></TableRow>)}{!commissionQuery.data?.length && <EmptyRow cols={4} message="Nenhuma comissão gerada." />}</TableBody></Table></CardContent></Card>}
        </>}

        {section === "gestao" && isAdmin && <>
          <SectionHeader eyebrow="ADMINISTRAÇÃO" title="Perfis, lembretes e relatórios" description="Gerencie acessos internos, acompanhe a fila de comunicação e consulte os indicadores consolidados." action={<Button className="primary-action" onClick={() => { setSupplyForm({ id: null, nome: "", unidade: "un", estoqueAtual: "", estoqueMinimo: "", custoUnitario: "" }); setShowSupplyForm(true); }}><PackagePlus /> Novo insumo</Button>} />
          <div className="metric-grid"><Metric icon={Users} label="Usuários cadastrados" value={String(usersQuery.data?.length ?? 0)} /><Metric icon={CalendarDays} label="Lembretes pendentes" value={String(reminderQuery.data?.filter((item) => item.status === "PENDENTE").length ?? 0)} /><Metric icon={CircleDollarSign} label="Faturamento no mês" value={currency(statsQuery.data?.faturamentoMes)} /><Metric icon={Activity} label="Ocupação de hoje" value={`${statsQuery.data?.taxaOcupacao ?? 0}%`} /></div>
          <div className="dashboard-grid finance-grid"><Card className="surface-card large-card"><CardHeader><CardTitle>Permissões de acesso</CardTitle><CardDescription>Defina o perfil operacional de cada conta autenticada.</CardDescription></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Usuário</TableHead><TableHead>E-mail</TableHead><TableHead>Perfil</TableHead><TableHead>Ativo</TableHead></TableRow></TableHeader><TableBody>{usersQuery.data?.map((account) => <TableRow key={account.id}><TableCell className="font-medium">{account.name ?? "Sem nome"}</TableCell><TableCell>{account.email ?? "—"}</TableCell><TableCell><Select value={account.role} onValueChange={(value) => updateUserRole.mutate({ id: account.id, role: value as "user" | "admin" | "recepcao" | "profissional" | "cliente", ativo: account.ativo })}><SelectTrigger className="h-8 min-w-35"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="admin">Gestor(a)</SelectItem><SelectItem value="recepcao">Recepção</SelectItem><SelectItem value="profissional">Profissional</SelectItem><SelectItem value="cliente">Cliente</SelectItem><SelectItem value="user">Cliente (padrão)</SelectItem></SelectContent></Select></TableCell><TableCell><Button size="sm" variant={account.ativo ? "outline" : "ghost"} onClick={() => updateUserRole.mutate({ id: account.id, role: account.role, ativo: !account.ativo })}>{account.ativo ? "Ativo" : "Inativo"}</Button></TableCell></TableRow>)}{!usersQuery.data?.length && <EmptyRow cols={4} message="Nenhuma conta disponível." />}</TableBody></Table></CardContent></Card><Card className="surface-card"><CardHeader><CardTitle>Fila de lembretes</CardTitle><CardDescription>Mensagens preparadas para o canal configurado.</CardDescription></CardHeader><CardContent className="space-y-2">{reminderQuery.data?.slice(0, 6).map((reminder) => <div className="expense-line" key={reminder.id}><div><strong>{reminder.destinatario}</strong><span>{dateTime(reminder.agendadoPara)}</span></div><StatusBadge value={reminder.status === "ENVIADO" ? "CONFIRMADA" : reminder.status === "CANCELADO" ? "CANCELADA" : "PENDENTE"} /></div>)}{!reminderQuery.data?.length && <p className="empty-copy">Não há lembretes enfileirados.</p>}</CardContent></Card></div>
          <Card className="surface-card mt-5"><CardHeader><div><p className="eyebrow">ESTOQUE CLÍNICO</p><CardTitle>Insumos e alertas de reposição</CardTitle><CardDescription>Controle a disponibilidade dos itens utilizados nos procedimentos.</CardDescription></div></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Insumo</TableHead><TableHead>Estoque atual</TableHead><TableHead>Mínimo</TableHead><TableHead>Custo unitário</TableHead><TableHead>Status</TableHead><TableHead /></TableRow></TableHeader><TableBody>{suppliesQuery.data?.map((supply) => <TableRow key={supply.id}><TableCell className="font-medium">{supply.nome}<small className="block">Unidade: {supply.unidade}</small></TableCell><TableCell>{Number(supply.estoqueAtual).toLocaleString("pt-BR")}</TableCell><TableCell>{Number(supply.estoqueMinimo).toLocaleString("pt-BR")}</TableCell><TableCell>{currency(supply.custoUnitario)}</TableCell><TableCell><span className={`status-badge ${supply.abaixoDoMinimo ? "status-danger" : "status-success"}`}>{supply.abaixoDoMinimo ? "Repor" : "Adequado"}</span></TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={() => { setSupplyForm({ id: supply.id, nome: supply.nome, unidade: supply.unidade, estoqueAtual: String(supply.estoqueAtual), estoqueMinimo: String(supply.estoqueMinimo), custoUnitario: String(supply.custoUnitario) }); setShowSupplyForm(true); }}>Editar</Button></TableCell></TableRow>)}{!suppliesQuery.data?.length && <EmptyRow cols={6} message="Nenhum insumo cadastrado." />}</TableBody></Table></CardContent></Card>
        </>}
      </main>
    </div>

    <Dialog open={showClientForm} onOpenChange={setShowClientForm}><DialogContent><DialogHeader><DialogTitle>Novo cliente</DialogTitle><DialogDescription>O cadastro cria automaticamente um prontuário clínico individual.</DialogDescription></DialogHeader><div className="form-stack"><Field label="Nome completo"><Input value={clientForm.nome} onChange={(event) => setClientForm({ ...clientForm, nome: event.target.value })} /></Field><div className="form-grid"><Field label="Telefone"><Input value={clientForm.telefone} onChange={(event) => setClientForm({ ...clientForm, telefone: event.target.value })} /></Field><Field label="Data de nascimento"><Input type="date" value={clientForm.dataNascimento} onChange={(event) => setClientForm({ ...clientForm, dataNascimento: event.target.value })} /></Field></div><Field label="E-mail"><Input type="email" value={clientForm.email} onChange={(event) => setClientForm({ ...clientForm, email: event.target.value })} /></Field><Field label="CPF (referência interna)"><Input value={clientForm.cpfHash} onChange={(event) => setClientForm({ ...clientForm, cpfHash: event.target.value })} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setShowClientForm(false)}>Cancelar</Button><Button className="primary-action" disabled={!clientForm.nome || createClient.isPending} onClick={() => createClient.mutate(clientForm)}>Salvar cliente</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={showSessionForm} onOpenChange={setShowSessionForm}><DialogContent><DialogHeader><DialogTitle>Novo agendamento</DialogTitle><DialogDescription>A conta a receber e os lembretes são preparados automaticamente.</DialogDescription></DialogHeader><div className="form-stack"><Field label="Cliente"><Select onValueChange={(value) => setSessionForm({ ...sessionForm, clienteId: value })}><SelectTrigger><SelectValue placeholder="Selecione o cliente" /></SelectTrigger><SelectContent>{clientsQuery.data?.map((client) => <SelectItem key={client.id} value={String(client.id)}>{client.nome}</SelectItem>)}</SelectContent></Select></Field><Field label="Procedimento"><Select onValueChange={(value) => { const service = servicesQuery.data?.find((item) => String(item.id) === value); setSessionForm({ ...sessionForm, servicoId: value, duracaoMin: String(service?.duracaoMin ?? 60) }); }}><SelectTrigger><SelectValue placeholder="Selecione o procedimento" /></SelectTrigger><SelectContent>{servicesQuery.data?.map((service) => <SelectItem key={service.id} value={String(service.id)}>{service.nome} · {currency(service.valor)}</SelectItem>)}</SelectContent></Select></Field>{isManager && <Field label="Profissional"><Select onValueChange={(value) => setSessionForm({ ...sessionForm, profissionalId: value })}><SelectTrigger><SelectValue placeholder="Selecione o profissional" /></SelectTrigger><SelectContent>{professionalsQuery.data?.map((professional) => <SelectItem key={professional.id} value={String(professional.id)}>{professional.name ?? "Profissional"}</SelectItem>)}</SelectContent></Select></Field>}<div className="form-grid"><Field label="Data e horário"><Input type="datetime-local" value={sessionForm.dataHoraInicio} onChange={(event) => setSessionForm({ ...sessionForm, dataHoraInicio: event.target.value })} /></Field><Field label="Duração"><Input type="number" min="10" value={sessionForm.duracaoMin} onChange={(event) => setSessionForm({ ...sessionForm, duracaoMin: event.target.value })} /></Field></div></div><DialogFooter><Button variant="outline" onClick={() => setShowSessionForm(false)}>Cancelar</Button><Button className="primary-action" disabled={!sessionForm.clienteId || !sessionForm.servicoId || !sessionForm.dataHoraInicio || createSession.isPending} onClick={() => createSession.mutate({ clienteId: Number(sessionForm.clienteId), servicoId: Number(sessionForm.servicoId), profissionalId: Number(sessionForm.profissionalId || user.id), dataHoraInicio: new Date(sessionForm.dataHoraInicio), duracaoMin: Number(sessionForm.duracaoMin) })}>Agendar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={showServiceForm} onOpenChange={setShowServiceForm}><DialogContent><DialogHeader><DialogTitle>Novo procedimento</DialogTitle><DialogDescription>Defina a base do serviço usada pela agenda e pelo financeiro.</DialogDescription></DialogHeader><div className="form-stack"><Field label="Nome"><Input value={serviceForm.nome} onChange={(event) => setServiceForm({ ...serviceForm, nome: event.target.value })} /></Field><div className="form-grid"><Field label="Valor"><Input value={serviceForm.valor} onChange={(event) => setServiceForm({ ...serviceForm, valor: event.target.value })} placeholder="0,00" /></Field><Field label="Duração (minutos)"><Input type="number" value={serviceForm.duracaoMin} onChange={(event) => setServiceForm({ ...serviceForm, duracaoMin: event.target.value })} /></Field></div><Field label="Descrição"><Textarea value={serviceForm.descricao} onChange={(event) => setServiceForm({ ...serviceForm, descricao: event.target.value })} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setShowServiceForm(false)}>Cancelar</Button><Button className="primary-action" disabled={!serviceForm.nome || !serviceForm.valor || createService.isPending} onClick={() => createService.mutate({ ...serviceForm, duracaoMin: Number(serviceForm.duracaoMin) })}>Salvar procedimento</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={showQuestionnaireForm} onOpenChange={setShowQuestionnaireForm}><DialogContent><DialogHeader><DialogTitle>Novo questionário de anamnese</DialogTitle><DialogDescription>Uma nova versão será publicada sob o código informado.</DialogDescription></DialogHeader><div className="form-stack"><div className="form-grid"><Field label="Código"><Input value={questionnaireForm.codigo} onChange={(event) => setQuestionnaireForm({ ...questionnaireForm, codigo: event.target.value })} placeholder="ANAMNESE-FACIAL" /></Field><Field label="Nome"><Input value={questionnaireForm.nome} onChange={(event) => setQuestionnaireForm({ ...questionnaireForm, nome: event.target.value })} /></Field></div><Field label="Descrição"><Textarea value={questionnaireForm.descricao} onChange={(event) => setQuestionnaireForm({ ...questionnaireForm, descricao: event.target.value })} /></Field><Field label="Primeira pergunta"><Textarea value={questionnaireForm.texto} onChange={(event) => setQuestionnaireForm({ ...questionnaireForm, texto: event.target.value })} placeholder="Ex.: Possui alguma alergia conhecida?" /></Field></div><DialogFooter><Button variant="outline" onClick={() => setShowQuestionnaireForm(false)}>Cancelar</Button><Button className="primary-action" disabled={!questionnaireForm.codigo || !questionnaireForm.nome || !questionnaireForm.texto || createQuestionnaire.isPending} onClick={() => createQuestionnaire.mutate({ codigo: questionnaireForm.codigo, nome: questionnaireForm.nome, descricao: questionnaireForm.descricao || undefined, perguntas: [{ texto: questionnaireForm.texto, tipoResposta: questionnaireForm.tipoResposta, obrigatoria: true }] })}>Publicar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={showEquipmentForm} onOpenChange={setShowEquipmentForm}><DialogContent><DialogHeader><DialogTitle>{equipmentForm.id ? "Editar equipamento" : "Novo equipamento"}</DialogTitle><DialogDescription>Cadastre recursos físicos para organização dos atendimentos e das manutenções.</DialogDescription></DialogHeader><div className="form-stack"><Field label="Nome"><Input value={equipmentForm.nome} onChange={(event) => setEquipmentForm({ ...equipmentForm, nome: event.target.value })} /></Field><div className="form-grid"><Field label="Tipo"><Input value={equipmentForm.tipo} onChange={(event) => setEquipmentForm({ ...equipmentForm, tipo: event.target.value })} placeholder="Ex.: Laser" /></Field><Field label="Localização"><Input value={equipmentForm.localizacao} onChange={(event) => setEquipmentForm({ ...equipmentForm, localizacao: event.target.value })} placeholder="Ex.: Sala 02" /></Field></div><Field label="Descrição"><Textarea value={equipmentForm.descricao} onChange={(event) => setEquipmentForm({ ...equipmentForm, descricao: event.target.value })} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setShowEquipmentForm(false)}>Cancelar</Button><Button className="primary-action" disabled={!equipmentForm.nome || createEquipment.isPending || updateEquipment.isPending} onClick={() => equipmentForm.id ? updateEquipment.mutate({ id: equipmentForm.id, nome: equipmentForm.nome, tipo: equipmentForm.tipo || undefined, localizacao: equipmentForm.localizacao || undefined, descricao: equipmentForm.descricao || undefined }) : createEquipment.mutate({ nome: equipmentForm.nome, tipo: equipmentForm.tipo || undefined, localizacao: equipmentForm.localizacao || undefined, descricao: equipmentForm.descricao || undefined })}>{equipmentForm.id ? "Salvar alterações" : "Cadastrar equipamento"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={showSupplyForm} onOpenChange={setShowSupplyForm}><DialogContent><DialogHeader><DialogTitle>{supplyForm.id ? "Editar insumo" : "Novo insumo"}</DialogTitle><DialogDescription>Defina o saldo disponível e o limite mínimo que deverá disparar o alerta de reposição.</DialogDescription></DialogHeader><div className="form-stack"><div className="form-grid"><Field label="Nome"><Input value={supplyForm.nome} onChange={(event) => setSupplyForm({ ...supplyForm, nome: event.target.value })} /></Field><Field label="Unidade"><Input value={supplyForm.unidade} onChange={(event) => setSupplyForm({ ...supplyForm, unidade: event.target.value })} placeholder="un, ml, g" /></Field></div><div className="form-grid"><Field label="Estoque atual"><Input inputMode="decimal" value={supplyForm.estoqueAtual} onChange={(event) => setSupplyForm({ ...supplyForm, estoqueAtual: event.target.value })} placeholder="0,00" /></Field><Field label="Estoque mínimo"><Input inputMode="decimal" value={supplyForm.estoqueMinimo} onChange={(event) => setSupplyForm({ ...supplyForm, estoqueMinimo: event.target.value })} placeholder="0,00" /></Field></div><Field label="Custo unitário"><Input inputMode="decimal" value={supplyForm.custoUnitario} onChange={(event) => setSupplyForm({ ...supplyForm, custoUnitario: event.target.value })} placeholder="0,00" /></Field></div><DialogFooter><Button variant="outline" onClick={() => setShowSupplyForm(false)}>Cancelar</Button><Button className="primary-action" disabled={!supplyForm.nome || !supplyForm.unidade || !supplyForm.estoqueAtual || !supplyForm.estoqueMinimo || !supplyForm.custoUnitario || createSupply.isPending || updateSupply.isPending} onClick={() => supplyForm.id ? updateSupply.mutate({ id: supplyForm.id, nome: supplyForm.nome, unidade: supplyForm.unidade, estoqueAtual: supplyForm.estoqueAtual, estoqueMinimo: supplyForm.estoqueMinimo, custoUnitario: supplyForm.custoUnitario }) : createSupply.mutate({ nome: supplyForm.nome, unidade: supplyForm.unidade, estoqueAtual: supplyForm.estoqueAtual, estoqueMinimo: supplyForm.estoqueMinimo, custoUnitario: supplyForm.custoUnitario })}>{supplyForm.id ? "Salvar alterações" : "Cadastrar insumo"}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={showExpenseForm} onOpenChange={setShowExpenseForm}><DialogContent><DialogHeader><DialogTitle>Novo lançamento de despesa</DialogTitle><DialogDescription>Registre a despesa para inclusão no caixa diário.</DialogDescription></DialogHeader><div className="form-stack"><Field label="Descrição"><Input value={expenseForm.descricao} onChange={(event) => setExpenseForm({ ...expenseForm, descricao: event.target.value })} /></Field><div className="form-grid"><Field label="Categoria"><Input value={expenseForm.categoria} onChange={(event) => setExpenseForm({ ...expenseForm, categoria: event.target.value })} /></Field><Field label="Valor"><Input value={expenseForm.valor} onChange={(event) => setExpenseForm({ ...expenseForm, valor: event.target.value })} placeholder="0,00" /></Field></div><Field label="Competência"><Input type="date" value={expenseForm.dataCompetencia} onChange={(event) => setExpenseForm({ ...expenseForm, dataCompetencia: event.target.value })} /></Field></div><DialogFooter><Button variant="outline" onClick={() => setShowExpenseForm(false)}>Cancelar</Button><Button className="primary-action" disabled={!expenseForm.descricao || !expenseForm.categoria || !expenseForm.valor || createExpense.isPending} onClick={() => createExpense.mutate(expenseForm)}>Salvar despesa</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function Metric({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string }) {
  return <Card className="metric-card"><CardContent><div className="metric-icon"><Icon /></div><div><p>{label}</p><strong>{value}</strong></div></CardContent></Card>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <div className="field"><Label>{label}</Label>{children}</div>;
}
